apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: provisioning-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: provisioning-trigger-binding
      name: provisioning-trigger
      template:
        ref: provisioning-trigger-template