kind: ConfigMap
apiVersion: v1
metadata:
  name: db-config
  #annotations:
  #  argocd.argoproj.io/sync-wave: "2"
data:
  build_tables.sql: |-
    alter table if exists Application 
       drop constraint if exists FKptjr8p27qnwtjpmknrmuyxlac;
    drop table if exists Application cascade;
    drop table if exists Config cascade;
    drop table if exists Department cascade;
    drop sequence if exists hibernate_sequence;

    create sequence hibernate_sequence start 1 increment 1;

    create table Application (
       id int8 not null,
        deployed boolean,
        description varchar(255),
        name varchar(255),
        department_id int8,
        primary key (id)
    );
    create table Config (
       id int8 not null,
        key varchar(255),
        value varchar(255),
        primary key (id)
    );

    create table Department (
       id int8 not null,
        aws boolean,
        azure boolean,
        dc boolean,
        description varchar(255),
        name varchar(255),
        provider varchar(255),
        status varchar(255),
        tenantType varchar(255),
        primary key (id)
    );

    alter table if exists Application 
      add constraint FKptjr8p27qnwtjpmknrmuyxlac 
      foreign key (department_id) 
      references Department;


  create_database.sql: CREATE DATABASE fsi;
  config.sql: insert into config (id,key,value) values (1,'dblocation','DC');
  data.sql: |-
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (1,'Fox Team','fox-team','deprived','ns',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (2,'Hawk Team','hawk-team','deprived','cluster',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (3,'Delta Team','delta-team','deprived','nodes',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (4,'Mes Team','mes-team','deprived','ns',false,false,false);
    insert into Department (id,description,name,status,tenantType,dc,aws,azure) values (5,'Zwarte Team','zwarte-team','deprived','ns',false,false,false);


    insert into Application (id,name,description,deployed,department_id) values (1,'Fixed-Wing','Fixed Wing Aircrafts',false,1);
    insert into Application (id,name,description,deployed,department_id) values (2,'Rotary-Wing','Rotary Wing Aircrafts',false,1);
    insert into Application (id,name,description,deployed,department_id) values (3,'Reconnaissance','Reconnaissance vehicles',false,1);
    insert into Application (id,name,description,deployed,department_id) values (4,'Fire-Support','Fire Support vehicles',false,1);
    insert into Application (id,name,description,deployed,department_id) values (5,'Tank','Tank',false,1);

    insert into Application (id,name,description,deployed,department_id) values (6,'Fixed-Wing','Fixed Wing Aircrafts',false,2);
    insert into Application (id,name,description,deployed,department_id) values (7,'Rotary-Wing','Rotary Wing Aircrafts',false,2);
    insert into Application (id,name,description,deployed,department_id) values (8,'Fire-Support','Fire Support vehicles',false,2);


    insert into Application (id,name,description,deployed,department_id) values (10,'Fire-Support','Fire Support vehicles',false,3);
    insert into Application (id,name,description,deployed,department_id) values (12,'Reconnaissance','Reconnaissance vehicles',false,3);

    insert into Application (id,name,description,deployed,department_id) values (13,'Fixed-Wing','Fixed Wing Aircrafts',false,4);
    insert into Application (id,name,description,deployed,department_id) values (14,'Rotary-Wing','Rotary Wing Aircrafts',false,4);
    insert into Application (id,name,description,deployed,department_id) values (15,'Navy-Ship','BattleShip',false,4);
