apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vulnerability-scanning-policy
  namespace: openshift-gitops
  annotations:
    policy.open-cluster-management.io/categories: SI System and Information Integrity
    policy.open-cluster-management.io/controls: SI-4 Information System Monitoring
    policy.open-cluster-management.io/description: Scan images in hub namsepace
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-imagemanifestvuln-sub
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: container-security-operator
                  namespace: openshift-operators
                spec:
                  name: container-security-operator
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-imagemanifestvuln-status
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: openshift-operators
                spec:
                  displayName: Red Hat Quay Container Security Operator
                status:
                  phase: Succeeded
          remediationAction: inform
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-imagemanifestvuln-example-imv
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - hub-ns
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: secscan.quay.redhat.com/v1alpha1
                kind: ImageManifestVuln
          remediationAction: inform
          severity: high
  remediationAction: enforce
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: all-clusters-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
    - default
status:
  conditions:
    - lastTransitionTime: 2024-08-04T15:40:24Z
      message: Placement configurations check pass
      reason: Succeedconfigured
      status: "False"
      type: PlacementMisconfigured
    - lastTransitionTime: 2024-08-04T15:43:32Z
      message: All cluster decisions scheduled
      reason: AllDecisionsScheduled
      status: "True"
      type: PlacementSatisfied
  decisionGroups:
    - clusterCount: 2
      decisionGroupIndex: 0
      decisionGroupName: ""
      decisions:
        - all-clusters-placement-decision-1
  numberOfSelectedClusters: 2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: vulnerability-scanning-policy-placement
  namespace: openshift-gitops
placementRef:
  name: all-clusters-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: vulnerability-scanning-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy