apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: pss-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - none
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: cs-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - none
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: treasury-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - none
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: legal-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - none
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: marketing-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: provider
              operator: In
              values:
                - none