kind: Secret
apiVersion: v1
metadata:
  name: postgresql
data:
  database-name: ZnNp #fsi
  database-password: QzBtcGxleFBAc3N3MHJk #C0mplexP@ssw0rd
  database-user: cG9zdGdyZXNAcG9zdGdyZXNxbHNlcnZlci1mc2k= #postgres@postgresqlserver-fsi
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: postgresqlserver-postgresqlserver-fsi
data:
  fullyQualifiedServerName: cG9zdGdyZXNxbHNlcnZlci1mc2kucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t
  fullyQualifiedUsername: cG9zdGdyZXNAcG9zdGdyZXNxbHNlcnZlci1mc2k=
  password: QzBtcGxleFBAc3N3MHJk
  postgreSqlServerName: cG9zdGdyZXNxbHNlcnZlci1mc2k=
  username: cG9zdGdyZXM=
  my-name: wael
type: Opaque
